version: '3.8'
services:
  db:
    container_name: postgres_project_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password     # Asegurarse de que esta contraseña sea la que deseas usar
      POSTGRES_DB: shop              
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"  
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
